---
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=3000"]
      - id: check-merge-conflict
      # - id: pretty-format-json
      - id: detect-private-key
  - repo: https://github.com/amperser/proselint/
    rev: 0.13.0
    hooks:
      - id: proselint
        # exclude: LICENSE|requirements
        files: \.(md|mdown|markdown|yml)$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.1
  #   hooks:
  #     - id: codespell
  #       args: [--ignore-words=.dictionary.txt]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
